---
title: The diminishing importance of nitrogen dioxide emissions from road vehicle exhaust
date: '2019-01-01'
author:
- David C. Carslaw
- Naomi J. Farren
- Adam R. Vaughan
- William S. Drysdale
- Stuart Young
- James D. Lee
categories:
- Journal Article
abstract: The direct emission of nitrogen dioxide (NO$_2$) from road vehicle exhaust has been an important contributor to
  near-road ambient concentrations of NO$_2$ in many European cities. Diesel vehicles and their use of emission control technologies
  such as Diesel Oxidation Catalysts, have dominated the emission of NO$_2$ from road vehicles. In this work, we summarise
  findings from recent vehicle emission remote sensing measurements in the UK that provide detailed information on the emissions
  of NO$_2$ and total NO$_x$ (NO$_2$ + NO). We show that while new diesel cars and light commercial vehicles are associated
  with high (typically 30%) proportions of NO$_2$/NO$_x$, the amount of absolute NO$_x$ and NO$_2$ emitted by most Euro 6
  vehicles has decreased substantially and that absolute emissions of NO$_2$ have been reducing since around 2007. Additionally,
  we find that the amount of NO$_2$ decreases as the vehicle mileage increases. Taken together, these factors have led to
  substantial reductions in emissions of NO$_2$ in recent years from light duty diesel vehicles, which has contributed to
  reduced roadside NO$_2$ concentrations. There is a need however for commonly used emission factor models to account for
  these changes in emissions of NO$_2$.
doi: 10.1016/j.aeaoa.2018.100002
publication: '*Atmospheric Environment: X*'
url_pdf: https://doi.org/10.1016%2Fj.aeaoa.2018.100002
featured: true
---

<div class="pub-badge">Featured</div>

## The diminishing importance of nitrogen dioxide emissions from road vehicle exhaust

<p class="pub-meta">David C. Carslaw, Naomi J. Farren, Adam R. Vaughan, William S. Drysdale, Stuart Young, James D. Lee</p>

_*Atmospheric Environment: X*_, 2019


<div class="pub-abstract">
The direct emission of nitrogen dioxide (NO$_2$) from road vehicle exhaust has been an important contributor to near-road ambient concentrations of NO$_2$ in many European cities. Diesel vehicles and their use of emission control technologies such as Diesel Oxidation Catalysts, have dominated the emission of NO$_2$ from road vehicles. In this work, we summarise findings from recent vehicle emission remote sensing measurements in the UK that provide detailed information on the emissions of NO$_2$ and total NO$_x$ (NO$_2$ + NO). We show that while new diesel cars and light commercial vehicles are associated with high (typically 30%) proportions of NO$_2$/NO$_x$, the amount of absolute NO$_x$ and NO$_2$ emitted by most Euro 6 vehicles has decreased substantially and that absolute emissions of NO$_2$ have been reducing since around 2007. Additionally, we find that the amount of NO$_2$ decreases as the vehicle mileage increases. Taken together, these factors have led to substantial reductions in emissions of NO$_2$ in recent years from light duty diesel vehicles, which has contributed to reduced roadside NO$_2$ concentrations. There is a need however for commonly used emission factor models to account for these changes in emissions of NO$_2$.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.aeaoa.2018.100002" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="https://doi.org/10.1016%2Fj.aeaoa.2018.100002" class="btn btn-outline-secondary btn-sm" target="_blank"><i class="bi bi-file-pdf"></i> PDF</a>
<a href="carslaw-2019.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
