---
title: Evaluation of the performance of different atmospheric chemical transport models and inter-comparison of nitrogen and
  sulphur deposition estimates for the UK
date: '2015-01-01'
author:
- A.J. Dore
- D.C. Carslaw
- C. Braban
- M. Cain
- C. Chemel
- C. Conolly
- R.G. Derwent
- S.J. Griffiths
- J. Hall
- G. Hayman
- S. Lawrence
- S.E. Metcalfe
- A. Redington
- D. Simpson
- M.A. Sutton
- P. Sutton
- Y.S. Tang
- M. Vieno
- M. Werner
- J.D. Whyatt
categories:
- Journal Article
abstract: An evaluation has been made of a number of contrasting atmospheric chemical transport models, of varying complexity,
  applied to estimate sulphur and nitrogen deposition in the UK. The models were evaluated by comparison with annually averaged
  measurements of gas, aerosol and precipitation concentrations from the national monitoring networks. The models were evaluated
  in relation to performance criteria. They were generally able to satisfy a criterion of "fitness for purpose" that at least
  50% of modelled concentrations should be within a factor of two of measured values. The second criterion, that the magnitude
  of the normalised mean bias should be less than 20%, was not always satisfied. Considering known uncertainties in measurement
  techniques, this criterion may be too strict. Overall, simpler models were able to give a good representation of measured
  gas concentrations whilst the use of dynamic meteorology, and complex photo-chemical reactions resulted in a generally better
  representation of measured aerosol and precipitation concentrations by more complex models. The models were compared graphically
  by plotting maps and cross-country transects of wet and dry deposition as well as calculating budgets of total wet and dry
  deposition to the UK for sulphur, oxidised nitrogen and reduced nitrogen. The total deposition to the UK varied by $\pm$22-36%
  amongst the different models depending on the deposition component. At a local scale estimates of both dry and wet deposition
  for individual 5 km $\times$ 5 km model grid squares were found to vary between the different models by up to a factor of
  4.
doi: 10.1016/j.atmosenv.2015.08.008
publication: '*Atmospheric Environment*'
---

## Evaluation of the performance of different atmospheric chemical transport models and inter-comparison of nitrogen and sulphur deposition estimates for the UK

<p class="pub-meta">A.J. Dore, D.C. Carslaw, C. Braban, M. Cain, C. Chemel, C. Conolly, R.G. Derwent, S.J. Griffiths, J. Hall, G. Hayman, S. Lawrence, S.E. Metcalfe, A. Redington, D. Simpson, M.A. Sutton, P. Sutton, Y.S. Tang, M. Vieno, M. Werner, J.D. Whyatt</p>

_*Atmospheric Environment*_, 2015


<div class="pub-abstract">
An evaluation has been made of a number of contrasting atmospheric chemical transport models, of varying complexity, applied to estimate sulphur and nitrogen deposition in the UK. The models were evaluated by comparison with annually averaged measurements of gas, aerosol and precipitation concentrations from the national monitoring networks. The models were evaluated in relation to performance criteria. They were generally able to satisfy a criterion of "fitness for purpose" that at least 50% of modelled concentrations should be within a factor of two of measured values. The second criterion, that the magnitude of the normalised mean bias should be less than 20%, was not always satisfied. Considering known uncertainties in measurement techniques, this criterion may be too strict. Overall, simpler models were able to give a good representation of measured gas concentrations whilst the use of dynamic meteorology, and complex photo-chemical reactions resulted in a generally better representation of measured aerosol and precipitation concentrations by more complex models. The models were compared graphically by plotting maps and cross-country transects of wet and dry deposition as well as calculating budgets of total wet and dry deposition to the UK for sulphur, oxidised nitrogen and reduced nitrogen. The total deposition to the UK varied by $\pm$22-36% amongst the different models depending on the deposition component. At a local scale estimates of both dry and wet deposition for individual 5 km $\times$ 5 km model grid squares were found to vary between the different models by up to a factor of 4.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.atmosenv.2015.08.008" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="carslaw-2015-a.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
