---
title: A trend analysis approach for air quality network data
date: '2019-04-01'
author:
- Polly E. Lang
- David C. Carslaw
- Sarah J. Moller
categories:
- Journal Article
abstract: Trend analysis of air pollutant concentrations becomes problematic when applied to data from air quality monitoring
  networks containing time series of differing lengths. The average trend from such data can be misleading due to biases in
  the monitoring network. For example, if new monitoring sites located in more polluted locations are added to a network,
  the introduction of these time series can leverage the trend upwards. A method for resolving this problem was developed,
  using rolling window regression to recursively calculate the change in pollutant concentration as a function of time, which
  can be used as a proxy for the true trend. The efficacy of the method was established by conducting simulations with known
  trends. The rolling change trend was shown to more accurately reflect the true trend than simply averaging the time series.
  Application of the technique to estimate trends in NO$_x$, NO$_2$ and NO$_2$/NO$_x$ concentrations at London roadside monitoring
  sites over the period 2000–2017 revealed clear differences from the simple average. In particular, a significant monotonic
  downward trend in NO$_x$ concentration was observed, in stark contrast to the average trend, which suggested little change
  in NO$_x$ concentration had occurred over the same period. By accurately representing trends using time series of different
  lengths, this method has the benefit of being able to describe changes in air quality for locations and time periods with
  otherwise insufficient data.
doi: 10.1016/j.aeaoa.2019.100030
publication: '*Atmospheric Environment: X*'
url_pdf: https://www.sciencedirect.com/science/article/pii/S2590162119300334
featured: true
---

<div class="pub-badge">Featured</div>

## A trend analysis approach for air quality network data

<p class="pub-meta">Polly E. Lang, David C. Carslaw, Sarah J. Moller</p>

_*Atmospheric Environment: X*_, 2019


<div class="pub-abstract">
Trend analysis of air pollutant concentrations becomes problematic when applied to data from air quality monitoring networks containing time series of differing lengths. The average trend from such data can be misleading due to biases in the monitoring network. For example, if new monitoring sites located in more polluted locations are added to a network, the introduction of these time series can leverage the trend upwards. A method for resolving this problem was developed, using rolling window regression to recursively calculate the change in pollutant concentration as a function of time, which can be used as a proxy for the true trend. The efficacy of the method was established by conducting simulations with known trends. The rolling change trend was shown to more accurately reflect the true trend than simply averaging the time series. Application of the technique to estimate trends in NO$_x$, NO$_2$ and NO$_2$/NO$_x$ concentrations at London roadside monitoring sites over the period 2000–2017 revealed clear differences from the simple average. In particular, a significant monotonic downward trend in NO$_x$ concentration was observed, in stark contrast to the average trend, which suggested little change in NO$_x$ concentration had occurred over the same period. By accurately representing trends using time series of different lengths, this method has the benefit of being able to describe changes in air quality for locations and time periods with otherwise insufficient data.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.aeaoa.2019.100030" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="https://www.sciencedirect.com/science/article/pii/S2590162119300334" class="btn btn-outline-secondary btn-sm" target="_blank"><i class="bi bi-file-pdf"></i> PDF</a>
<a href="Lang-2019.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
