---
title: Conditional bivariate probability function for source identification
date: '2014-01-01'
author:
- I. Uria-Tellaetxe
- D.C. Carslaw
categories:
- Journal Article
abstract: In this paper a new receptor modelling method is developed to identify and characterise emission sources. The method
  is an extension of the commonly used conditional probability function (CPF). The CPF approach is extended to the bivariate
  case to produce a conditional bivariate probability function (CBPF) plot using wind speed as a third variable plotted on
  the radial axis. The bivariate case provides more information on the type of sources being identified by providing important
  dispersion characteristic information. By considering intervals of concentration, considerably more source information can
  be revealed that is absent in the basic CPF or CBPF. We demonstrate the application of the approach by considering an area
  of high source complexity, where many new sources can be identified and characterised compared with currently used techniques.
  Dispersion model simulations are undertaken to verify the approach. The technique has been made available through the openair
  R package.
doi: 10.1016/j.envsoft.2014.05.002
publication: '*Environmental Modelling and Software*'
---

## Conditional bivariate probability function for source identification

<p class="pub-meta">I. Uria-Tellaetxe, D.C. Carslaw</p>

_*Environmental Modelling and Software*_, 2014


<div class="pub-abstract">
In this paper a new receptor modelling method is developed to identify and characterise emission sources. The method is an extension of the commonly used conditional probability function (CPF). The CPF approach is extended to the bivariate case to produce a conditional bivariate probability function (CBPF) plot using wind speed as a third variable plotted on the radial axis. The bivariate case provides more information on the type of sources being identified by providing important dispersion characteristic information. By considering intervals of concentration, considerably more source information can be revealed that is absent in the basic CPF or CBPF. We demonstrate the application of the approach by considering an area of high source complexity, where many new sources can be identified and characterised compared with currently used techniques. Dispersion model simulations are undertaken to verify the approach. The technique has been made available through the openair R package.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.envsoft.2014.05.002" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="carslaw-2014.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
