---
title: Introduction to the special issue "In-depth study of air pollution sources and processes within Beijing and its surrounding
  region (APHH-Beijing)"
date: '2019-01-01'
author:
- Z. Shi
- T. Vu
- S. Kotthaus
- R. M. Harrison
- S. Grimmond
- S. Yue
- T. Zhu
- J. Lee
- Y. Han
- M. Demuzere
- R. E. Dunmore
- L. Ren
- D. Liu
- Y. Wang
- O. Wild
- J. Allan
- W. J. Acton
- J. Barlow
- B. Barratt
- D. Beddows
- W. J. Bloss
- G. Calzolai
- D. Carruthers
- D. C. Carslaw
- Q. Chan
- L. Chatzidiakou
- Y. Chen
- L. Crilley
- H. Coe
- T. Dai
- R. Doherty
- F. Duan
- P. Fu
- B. Ge
- M. Ge
- D. Guan
- J. F. Hamilton
- K. He
- M. Heal
- D. Heard
- C. N. Hewitt
- M. Hollaway
- M. Hu
- D. Ji
- X. Jiang
- R. Jones
- M. Kalberer
- F. J. Kelly
- L. Kramer
- B. Langford
- C. Lin
- A. C. Lewis
- J. Li
- W. Li
- H. Liu
- J. Liu
- M. Loh
- K. Lu
- F. Lucarelli
- G. Mann
- G. McFiggans
- M. R. Miller
- G. Mills
- P. Monk
- E. Nemitz
- F. O'Connor
- B. Ouyang
- P. I. Palmer
- C. Percival
- O. Popoola
- C. Reeves
- A. R. Rickard
- L. Shao
- G. Shi
- D. Spracklen
- D. Stevenson
- Y. Sun
- Z. Sun
- S. Tao
- S. Tong
- Q. Wang
- W. Wang
- X. Wang
- X. Wang
- Z. Wang
- L. Wei
- L. Whalley
- X. Wu
- Z. Wu
- P. Xie
- F. Yang
- Q. Zhang
- Y. Zhang
- Y. Zhang
- M. Zheng
categories:
  - research
  - air quality
description: 'Introduction to the APHH-Beijing special issue, presenting the coordinated multi-disciplinary campaign to study air pollution sources and processes within Beijing and its surrounding region.'
doi: 10.5194/acp-19-7519-2019
publication: '*Atmospheric Chemistry and Physics*'
url_pdf: https://www.atmos-chem-phys.net/19/7519/2019/
---

## Introduction to the special issue "In-depth study of air pollution sources and processes within Beijing and its surrounding region (APHH-Beijing)"

<p class="pub-meta">Z. Shi, T. Vu, S. Kotthaus, R. M. Harrison, S. Grimmond, S. Yue, T. Zhu, J. Lee, Y. Han, M. Demuzere, R. E. Dunmore, L. Ren, D. Liu, Y. Wang, O. Wild, J. Allan, W. J. Acton, J. Barlow, B. Barratt, D. Beddows, W. J. Bloss, G. Calzolai, D. Carruthers, D. C. Carslaw, Q. Chan, L. Chatzidiakou, Y. Chen, L. Crilley, H. Coe, T. Dai, R. Doherty, F. Duan, P. Fu, B. Ge, M. Ge, D. Guan, J. F. Hamilton, K. He, M. Heal, D. Heard, C. N. Hewitt, M. Hollaway, M. Hu, D. Ji, X. Jiang, R. Jones, M. Kalberer, F. J. Kelly, L. Kramer, B. Langford, C. Lin, A. C. Lewis, J. Li, W. Li, H. Liu, J. Liu, M. Loh, K. Lu, F. Lucarelli, G. Mann, G. McFiggans, M. R. Miller, G. Mills, P. Monk, E. Nemitz, F. O'Connor, B. Ouyang, P. I. Palmer, C. Percival, O. Popoola, C. Reeves, A. R. Rickard, L. Shao, G. Shi, D. Spracklen, D. Stevenson, Y. Sun, Z. Sun, S. Tao, S. Tong, Q. Wang, W. Wang, X. Wang, X. Wang, Z. Wang, L. Wei, L. Whalley, X. Wu, Z. Wu, P. Xie, F. Yang, Q. Zhang, Y. Zhang, Y. Zhang, M. Zheng</p>

_*Atmospheric Chemistry and Physics*_, 2019


## Abstract

<div class="pub-abstract">
The Atmospheric Pollution and Human Health in a Chinese Megacity (APHH-Beijing) programme is an international collaborative project focusing on understanding the sources, processes and health effects of air pollution in the Beijing megacity. APHH-Beijing brings together leading China and UK research groups, state-of-the-art infrastructure and air quality models to work on four research themes: (1) sources and emissions of air pollutants; (2) atmospheric processes affecting urban air pollution; (3) air pollution exposure and health impacts; and (4) interventions and solutions. Themes 1 and 2 are closely integrated and support Theme 3, while Themes 1–3 provide scientific data for Theme 4 to develop cost-effective air pollution mitigation solutions. This paper provides an introduction to (i) the rationale of the APHH-Beijing programme and (ii) the measurement and modelling activities performed as part of it. In addition, this paper introduces the meteorology and air quality conditions during two joint intensive field campaigns – a core integration activity in APHH-Beijing. The coordinated campaigns provided observations of the atmospheric chemistry and physics at two sites: (i) the Institute of Atmospheric Physics in central Beijing and (ii) Pinggu in rural Beijing during 10 November–10 December 2016 (winter) and 21 May–22 June 2017 (summer). The campaigns were complemented by numerical modelling and automatic air quality and low-cost sensor observations in the Beijing megacity. In summary, the paper provides background information on the APHH-Beijing programme and sets the scene for more focused papers addressing specific aspects, processes and effects of air pollution in Beijing.
</div>

<div class="pub-links">
<a href="https://doi.org/10.5194/acp-19-7519-2019" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="https://www.atmos-chem-phys.net/19/7519/2019/" class="btn btn-outline-secondary btn-sm" target="_blank"><i class="bi bi-file-pdf"></i> PDF</a>
<a href="acp-19-7519-2019.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
