---
title: Characterising and understanding emission sources using bivariate polar plots and k-means clustering
date: '2013-01-01'
author:
- D.C. Carslaw
- S.D. Beevers
categories:
- Journal Article
abstract: This paper develops the idea of bivariate polar plots as a method for source detection and characterisation. Bivariate
  polar plots provide a graphical method for showing the joint wind speed, wind direction dependence of air pollutant concentrations.
  Bivariate polar plots provide an effective graphical means of discriminating different source types and characteristics.
  In the current work we apply k-means clustering techniques directly to bivariate polar plots to identify and group similar
  features. The technique is analogous to clustering applied to back trajectories at the regional scale. When applied to data
  from a monitoring site with high source complexity it is shown that the technique is able to identify important clusters
  in ambient monitoring data that additional analysis shows to exhibit different source characteristics. Importantly, this
  paper links identified clusters to known emission characteristics to confirm the inferences made in the analysis. The approaches
  developed should have wide application to the analysis of air pollution monitoring data and have been made freely available
  as part of the openair R package.
doi: 10.1016/j.envsoft.2012.09.005
publication: '*Environmental Modelling and Software*'
---

## Characterising and understanding emission sources using bivariate polar plots and k-means clustering

<p class="pub-meta">D.C. Carslaw, S.D. Beevers</p>

_*Environmental Modelling and Software*_, 2013


<div class="pub-abstract">
This paper develops the idea of bivariate polar plots as a method for source detection and characterisation. Bivariate polar plots provide a graphical method for showing the joint wind speed, wind direction dependence of air pollutant concentrations. Bivariate polar plots provide an effective graphical means of discriminating different source types and characteristics. In the current work we apply k-means clustering techniques directly to bivariate polar plots to identify and group similar features. The technique is analogous to clustering applied to back trajectories at the regional scale. When applied to data from a monitoring site with high source complexity it is shown that the technique is able to identify important clusters in ambient monitoring data that additional analysis shows to exhibit different source characteristics. Importantly, this paper links identified clusters to known emission characteristics to confirm the inferences made in the analysis. The approaches developed should have wide application to the analysis of air pollution monitoring data and have been made freely available as part of the openair R package.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.envsoft.2012.09.005" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="carslaw-2013-a.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
