---
title: Strong temperature dependence for light-duty diesel vehicle NO$_x$ emissions
date: '2019-05-21'
author:
- Stuart K. Grange
- Naomi J. Farren
- Adam R. Vaughan
- Rebecca A. Rose
- David C. Carslaw
categories:
- Journal Article
abstract: Diesel-powered road vehicles are important sources for nitrogen oxide (NO$_x$) emissions and the European passenger
  fleet is highly dieselised, which has resulted in many European roadside environments being non-compliant with legal air
  quality standards for nitrogen dioxide (NO$_2$). Based on vehicle emission remote sensing data for 300 000 light-duty vehicles
  across the United Kingdom, light-duty diesel NO$_x$ emissions were found to be highly dependent on ambient temperature with
  low temperatures resulting in higher NO$_x$ emissions, i.e., a "low temperature NO$_x$ emission penalty" was identified.
  This feature was not observed for gasoline-powered vehicles. Older Euro 3 to 5 diesel vehicles emitted NO$_x$ similarly,
  but vehicles compliant with the latest Euro 6 emission standard, emitted less NO$_x$ than older vehicles and demonstrated
  less of an ambient temperature dependence. This ambient temperature dependence is overlooked in current emission inventories,
  but is of importance from an air quality perspective. Owing to Europe's climate, a predicted average of 38 % more NO$_x$
  emissions have burdened Europe when compared to temperatures encountered in laboratory test cycles. However, owing to the
  progressive elimination of vehicles demonstrating the most severe low temperature NO$_x$ penalty, light-duty diesel NO$_x$
  emissions are likely to decrease more rapidly throughout Europe than currently thought.
doi: 10.1021/acs.est.9b01024
publication: '*Environmental Science & Technology*'
url_pdf: https://doi.org/10.1021/acs.est.9b01024
featured: true
---

<div class="pub-badge">Featured</div>

## Strong temperature dependence for light-duty diesel vehicle NO$_x$ emissions

<p class="pub-meta">Stuart K. Grange, Naomi J. Farren, Adam R. Vaughan, Rebecca A. Rose, David C. Carslaw</p>

_*Environmental Science & Technology*_, 2019


<div class="pub-abstract">
Diesel-powered road vehicles are important sources for nitrogen oxide (NO$_x$) emissions and the European passenger fleet is highly dieselised, which has resulted in many European roadside environments being non-compliant with legal air quality standards for nitrogen dioxide (NO$_2$). Based on vehicle emission remote sensing data for 300 000 light-duty vehicles across the United Kingdom, light-duty diesel NO$_x$ emissions were found to be highly dependent on ambient temperature with low temperatures resulting in higher NO$_x$ emissions, i.e., a "low temperature NO$_x$ emission penalty" was identified. This feature was not observed for gasoline-powered vehicles. Older Euro 3 to 5 diesel vehicles emitted NO$_x$ similarly, but vehicles compliant with the latest Euro 6 emission standard, emitted less NO$_x$ than older vehicles and demonstrated less of an ambient temperature dependence. This ambient temperature dependence is overlooked in current emission inventories, but is of importance from an air quality perspective. Owing to Europe's climate, a predicted average of 38 % more NO$_x$ emissions have burdened Europe when compared to temperatures encountered in laboratory test cycles. However, owing to the progressive elimination of vehicles demonstrating the most severe low temperature NO$_x$ penalty, light-duty diesel NO$_x$ emissions are likely to decrease more rapidly throughout Europe than currently thought.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1021/acs.est.9b01024" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="https://doi.org/10.1021/acs.est.9b01024" class="btn btn-outline-secondary btn-sm" target="_blank"><i class="bi bi-file-pdf"></i> PDF</a>
</div>
