---
title: The importance of high vehicle power for passenger car emissions
date: '2013-01-01'
author:
- D.C. Carslaw
- M.L. Williams
- J.E. Tate
- S.D. Beevers
categories:
- Journal Article
abstract: In this paper we use a quantile regression technique to explore the emissions characteristics of petrol and diesel
  passenger cars to reveal the importance of high vehicle power on exhaust emissions. A large database of $\approx$67,000
  passenger cars from vehicle emission remote sensing data was used from surveys from several campaigns around the UK. Most
  previous remote sensing studies have focused on presenting mean emission estimates by vehicle type over time. However, as
  shown in the current work, considerably more insight can be gained into vehicle emission characteristics if techniques are
  used that can describe and model the full distribution of vehicle emissions as a function of important explanatory variables.
  For post-2000 model year (Euro 3–5) diesel cars it is shown that there is a strong dependence of vehicle specific power
  for emissions of NO$_x$ that was absent in earlier models and is absent for other pollutants such as CO, hydrocarbons and
  ‘smoke’. Furthermore, we also find a stronger dependence on vehicle specific power for older catalyst-equipped petrol vehicles
  (Euro 1/2) on emissions of NO$_x$ that is less important for other emissions such as CO and hydrocarbons. Moreover, it is
  shown that while the rated maximum power output of petrol cars has remained almost constant over the past 15–20 years, the
  power output from diesel cars has increased markedly by about 50%. These results suggest that changes to vehicle technology,
  driving conditions and driver behaviour have become more important determinants of passenger car NO$_x$ emissions in recent
  years and may help explain why urban ambient concentrations of NO$_x$ have not decreased as much as anticipated.
doi: 10.1016/j.atmosenv.2012.11.033
publication: '*Atmospheric Environment*'
---

## The importance of high vehicle power for passenger car emissions

<p class="pub-meta">D.C. Carslaw, M.L. Williams, J.E. Tate, S.D. Beevers</p>

_*Atmospheric Environment*_, 2013


<div class="pub-abstract">
In this paper we use a quantile regression technique to explore the emissions characteristics of petrol and diesel passenger cars to reveal the importance of high vehicle power on exhaust emissions. A large database of $\approx$67,000 passenger cars from vehicle emission remote sensing data was used from surveys from several campaigns around the UK. Most previous remote sensing studies have focused on presenting mean emission estimates by vehicle type over time. However, as shown in the current work, considerably more insight can be gained into vehicle emission characteristics if techniques are used that can describe and model the full distribution of vehicle emissions as a function of important explanatory variables. For post-2000 model year (Euro 3–5) diesel cars it is shown that there is a strong dependence of vehicle specific power for emissions of NO$_x$ that was absent in earlier models and is absent for other pollutants such as CO, hydrocarbons and ‘smoke’. Furthermore, we also find a stronger dependence on vehicle specific power for older catalyst-equipped petrol vehicles (Euro 1/2) on emissions of NO$_x$ that is less important for other emissions such as CO and hydrocarbons. Moreover, it is shown that while the rated maximum power output of petrol cars has remained almost constant over the past 15–20 years, the power output from diesel cars has increased markedly by about 50%. These results suggest that changes to vehicle technology, driving conditions and driver behaviour have become more important determinants of passenger car NO$_x$ emissions in recent years and may help explain why urban ambient concentrations of NO$_x$ have not decreased as much as anticipated.
</div>


<div class="pub-links">
<a href="https://doi.org/10.1016/j.atmosenv.2012.11.033" class="btn btn-primary btn-sm" target="_blank"><i class="bi bi-box-arrow-up-right"></i> DOI</a>
<a href="carslaw-2013-d.bib" class="btn btn-outline-secondary btn-sm"><i class="bi bi-download"></i> BibTeX</a>
</div>
